-- MySQL Script generated by MySQL Workbench
-- Tue Mar 26 10:24:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema order_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `order_db` ;

-- -----------------------------------------------------
-- Schema order_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `order_db` DEFAULT CHARACTER SET utf8 ;
USE `order_db` ;

-- -----------------------------------------------------
-- Table `order_db`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_db`.`state` ;

CREATE TABLE IF NOT EXISTS `order_db`.`state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `order_db`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `order_db`.`order` ;

CREATE TABLE IF NOT EXISTS `order_db`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `state_id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `notes` VARCHAR(1000) NULL,
  `order_date` DATETIME NULL,
  `total` DECIMAL(10,2) NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `state_id`),
  INDEX `fk_order_state_idx` (`state_id` ASC),
  CONSTRAINT `fk_order_state`
    FOREIGN KEY (`state_id`)
    REFERENCES `order_db`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
